openapi: 3.0.0
info:
  title: Music Tracks API
  description: Simple REST API for managing music libraries
  version: 0.1.0
servers:
  - url: http://127.0.0.1:8080/api
    description: Local development server
tags:
  - name: Tracks
    description: Operations related to music tracks
paths:
  /tracks/{id}:
    get:
      summary: Returns a track by ID
      tags: [Tracks]
      parameters:
        - in: path
          name: id
          schema: { type: integer }
          required: true
      responses:
        "200": { $ref: "#/components/responses/TrackResource" }
        "404": { $ref: "#/components/responses/NotFound" }
        default: { $ref: "#/components/responses/InternalError" }
  /tracks/:
    get:
      summary: Returns a list of all tracks
      tags: [Tracks]
      responses:
        "200": { $ref: "#/components/responses/TracksResource" }
        default: { $ref: "#/components/responses/InternalError" }
    post:
      summary: Creates a new track
      tags: [Tracks]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/NewTrackResource" }
      responses:
        "201": { $ref: "#/components/responses/TrackResource" }
        "400": { $ref: "#/components/responses/BadRequest" }
        default: { $ref: "#/components/responses/InternalError" }
components:
  responses:
    TrackResource:
      description: OK
      content:
        application/json:
          schema: { $ref: "#/components/schemas/TrackResource" }
    TracksResource:
      description: OK
      content:
        application/json:
          schema: { $ref: "#/components/schemas/TracksResource" }
    BadRequest:
      description: Request is ill-formed
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Error" }
    NotFound:
      description: Referencing a non-existent resource
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Error" }
    InternalError:
      description: Reports an internal server failure
      content:
        application/json:
          schema: { $ref: "#/components/schemas/Error" }
  schemas:
    Track: { $ref: "models.json#/$def/Track" }
    TrackInfo: { $ref: "models.json#/$def/TrackInfo" }
    NewTrackResource: { $ref: "models.json#/$def/NewTrackResource" }
    TrackResource: { $ref: "models.json#/$def/TrackResource" }
    TracksResource: { $ref: "models.json#/$def/TracksResource" }
    Error: { $ref: "models.json#/$def/Error" }
